In [2]:
import tweepy
import GetOldTweets3 as got
import twitterscraper as twit
import pandas as pd
import requests
import json

## 1.Twitter Authentication

In [33]:
APIkey= "DkhEorgjmvqiRRN5LN1tlVw6C"
APIsecret= "Boqs9QnqOkIGgpqklUNbghwXnDwZqgMjjZPtLnMb3ljXZadIad"
Bearertoken="dAAAAAAAAAAAAAAAAAAAAAK%2BjGAEAAAAAmPQmomKgjzTHJxmep4yBdESAwZk%3DEsTadzSWviOpiNBUBGSyoctKPK0aNvcCwyNqoHZawzPazgQmaQ"
Accesstoken="1285224050705432578-ZLa0f9VZu07hn9jMN9UQgsLQIYA5br"
Accesssecret="tjOH3GyzsHhFpq044EA9aQeaJQvcxC2811Fp2rEJ2tpF2"

In [34]:
auth= tweepy.OAuthHandler(APIkey, APIsecret,Bearertoken)
auth.set_access_token(Accesstoken, Accesssecret)

In [35]:
api = tweepy.API(auth)

## 2.

### listing the Twitter Directory to see which call methods can be used
#### to get tweets and hashtags, use :
* 'trends_available' 
* 'trends_closest'
* 'trends_place'
##### see usability for  'related_results'
http://docs.tweepy.org/en/latest/api.html#API.search

In [5]:
methods=[dir(api)]
print(methods)

[['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_add_list_members', '_lookup_friendships', '_pack_image', '_remove_list_members', '_send_direct_message', 'add_list_member', 'add_list_members', 'api_root', 'auth', 'blocks', 'blocks_ids', 'cache', 'compression', 'configuration', 'create_block', 'create_favorite', 'create_friendship', 'create_list', 'create_media_metadata', 'create_mute', 'create_saved_search', 'destroy_block', 'destroy_direct_message', 'destroy_favorite', 'destroy_friendship', 'destroy_list', 'destroy_mute', 'destroy_saved_search', 'destroy_status', 'favorites', 'followers', 'followers_ids', 'friends', 'friends_ids', 'friendships_incoming', 'friendships_outgoing', 'geo_id', 'geo_search', 'geo_similar_places', 'get_direct_message', 'get_list', 'get_oembed', 'get_saved_search', 'get_settings', 'get_status', 'get_user', 'home_timeline', 'host', 'list_direct_messages', 'list_members', 'list_subscribers', 'list_timeline', 'lists_all', 'lists_memberships', 'lists_subscriptions', 'lookup_friendships', 'lookup_users', 'me', 'media_upload', 'mentions_timeline', 'mutes', 'mutes_ids', 'parser', 'proxy', 'rate_limit_status', 'related_results', 'remove_list_member', 'remove_list_members', 'report_spam', 'retry_count', 'retry_delay', 'retry_errors', 'retweet', 'retweeters', 'retweets', 'retweets_of_me', 'reverse_geocode', 'saved_searches', 'search', 'search_host', 'search_root', 'search_users', 'send_direct_message', 'set_settings', 'show_friendship', 'show_list_member', 'show_list_subscriber', 'statuses_lookup', 'subscribe_list', 'supported_languages', 'timeout', 'trends_available', 'trends_closest', 'trends_place', 'unretweet', 'unsubscribe_list', 'update_list', 'update_profile', 'update_profile_background_image', 'update_profile_banner', 'update_profile_image', 'update_status', 'update_with_media', 'upload_host', 'upload_root', 'user_timeline', 'verify_credentials', 'wait_on_rate_limit', 'wait_on_rate_limit_notify']]

#### as Yahoo geo ID was unattainable, decided to get geo ID via trends available which lists the "WOEID" needed to run queries

In [6]:
locationID=pd.DataFrame(data=api.trends_available())
locationID

,name,placeType,url,parentid,country,woeid,countryCode
0,Worldwide,"{'code': 19, 'name': 'Supername'}",http://where.yahooapis.com/v1/place/1,0,,1,None
1,Winnipeg,"{'code': 7, 'name': 'Town'}",http://where.yahooapis.com/v1/place/2972,23424775,Canada,2972,CA
2,Ottawa,"{'code': 7, 'name': 'Town'}",http://where.yahooapis.com/v1/place/3369,23424775,Canada,3369,CA
3,Quebec,"{'code': 7, 'name': 'Town'}",http://where.yahooapis.com/v1/place/3444,23424775,Canada,3444,CA
4,Montreal,"{'code': 7, 'name': 'Town'}",http://where.yahooapis.com/v1/place/3534,23424775,Canada,3534,CA
...,...,...,...,...,...,...,...
462,Vietnam,"{'code': 12, 'name': 'Country'}",http://where.yahooapis.com/v1/place/23424984,1,Vietnam,23424984,VN
463,Petaling,"{'code': 7, 'name': 'Town'}",http://where.yahooapis.com/v1/place/56013632,23424901,Malaysia,56013632,MY
464,Hulu Langat,"{'code': 7, 'name': 'Town'}",http://where.yahooapis.com/v1/place/56013645,23424901,Malaysia,56013645,MY
465,Ahsa,"{'code': 9, 'name': 'Unknown'}",http://where.yahooapis.com/v1/place/56120136,23424938,Saudi Arabia,56120136,SA
466,Okayama,"{'code': 7, 'name': 'Town'}",http://where.yahooapis.com/v1/place/90036018,23424856,Japan,90036018,JP

### get Geo Location for United States

In [7]:
stateIDs=locationID[locationID['country']=='United States']
stateIDs
##name seems to be the best identifyer for country, we can see that parent ID of 1 also means it's a country versus a location within

,name,placeType,url,parentid,country,woeid,countryCode
335,Albuquerque,"{'code': 7, 'name': 'Town'}",http://where.yahooapis.com/v1/place/2352824,23424977,United States,2352824,US
336,Atlanta,"{'code': 7, 'name': 'Town'}",http://where.yahooapis.com/v1/place/2357024,23424977,United States,2357024,US
337,Austin,"{'code': 7, 'name': 'Town'}",http://where.yahooapis.com/v1/place/2357536,23424977,United States,2357536,US
338,Baltimore,"{'code': 7, 'name': 'Town'}",http://where.yahooapis.com/v1/place/2358820,23424977,United States,2358820,US
339,Baton Rouge,"{'code': 7, 'name': 'Town'}",http://where.yahooapis.com/v1/place/2359991,23424977,United States,2359991,US
...,...,...,...,...,...,...,...
394,Tampa,"{'code': 7, 'name': 'Town'}",http://where.yahooapis.com/v1/place/2503863,23424977,United States,2503863,US
395,Tucson,"{'code': 7, 'name': 'Town'}",http://where.yahooapis.com/v1/place/2508428,23424977,United States,2508428,US
396,Virginia Beach,"{'code': 7, 'name': 'Town'}",http://where.yahooapis.com/v1/place/2512636,23424977,United States,2512636,US
397,Washington,"{'code': 7, 'name': 'Town'}",http://where.yahooapis.com/v1/place/2514815,23424977,United States,2514815,US
460,United States,"{'code': 12, 'name': 'Country'}",http://where.yahooapis.com/v1/place/23424977,1,United States,23424977,US

In [8]:
locationID[locationID['name']=='United States']

,name,placeType,url,parentid,country,woeid,countryCode
460,United States,"{'code': 12, 'name': 'Country'}",http://where.yahooapis.com/v1/place/23424977,1,United States,23424977,US

## 2.Extracting tweets and old tweets

## As Twitter has a max of 1 week old tweets, decided to use the GetOldTweets3 library

Python classes

    Tweet: Model class that describes a specific tweet.
        id (str)
        permalink (str)
        username (str)
        to (str)
        text (str)
        date (datetime) in UTC
        retweets (int)
        favorites (int)
        mentions (str)
        hashtags (str)
        geo (str)

    TweetManager: A manager class to help getting tweets in Tweet's model.
        getTweets (TwitterCriteria): Return the list of tweets retrieved by using an instance of TwitterCriteria.

    TwitterCriteria: A collection of search parameters to be used together with TweetManager.
        setUsername (str or iterable): An optional specific username(s) from a twitter account (with or without "@").
        setSince (str. "yyyy-mm-dd"): A lower bound date (UTC) to restrict search.
        setUntil (str. "yyyy-mm-dd"): An upper bound date (not included) to restrict search.
        setQuerySearch (str): A query text to be matched.
        setTopTweets (bool): If True only the Top Tweets will be retrieved.
        setNear(str): A reference location area from where tweets were generated.
        setWithin (str): A distance radius from "near" location (e.g. 15mi).
        setMaxTweets (int): The maximum number of tweets to be retrieved. If this number is unsetted or lower than 1 all possible tweets will be retrieved.
id 
permalinkusername
to
text
date
retweets
favorites
mentions
hashtags
geo

In [113]:
criteria = got.manager.TweetCriteria().setQuerySearch('#baking').setMaxTweets(1).setSince('2019-07-01').setUntil('2020-07-01')
tweets = got.manager.TweetManager.getTweets(criteria)
for tweet in tweets:
    print(dir(tweet))
    print(tweet.__dict__)

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'author_id', 'date', 'favorites', 'formatted_date', 'geo', 'hashtags', 'id', 'mentions', 'permalink', 'replies', 'retweets', 'text', 'to', 'urls', 'username']
{'username': 'PirateMomCG', 'to': None, 'text': 'Peach strawberry cobbler in the oven #cobbler #baking #quarantine15 #yum #saturnpeaches ', 'retweets': 0, 'favorites': 1, 'replies': 2, 'id': '1278116061108469760', 'permalink': 'https://twitter.com/PirateMomCG/status/1278116061108469760', 'author_id': 1160216723645194241, 'date': datetime.datetime(2020, 6, 30, 23, 59, 49, tzinfo=datetime.timezone.utc), 'formatted_date': 'Tue Jun 30 23:59:49 +0000 2020', 'hashtags': '#cobbler #baking #quarantine15 #yum #saturnpeaches', 'mentions': '', 'geo': '', 'urls': ''}

In [101]:
criteria = got.manager.TweetCriteria().setQuerySearch('#baking').setMaxTweets(10000).setSince('2019-07-01').setUntil('2020-07-30')
tweets = got.manager.TweetManager.getTweets(criteria)

baking_set = [[
                tweet.id, 
                tweet.username,
                tweet.author_id,
                tweet.text,
                tweet.date,
                tweet.geo,
                tweet.hashtags,                
                tweet.permalink,
                    ] for tweet in tweets]

In [102]:
bakingdata=pd.DataFrame(baking_set, columns = ['id','username','author_id','text','date','geo','hashtags','permalink']).sort_values('date', ascending=False).reset_index(drop='true')

In [103]:
bakingdata

,id,username,author_id,text,date,geo,hashtags,permalink
0,1288624943647936513,catfishman,14279889,Got bored and had the munchies so I made garli...,2020-07-29 23:58:22+00:00,,#bread #baking #getbaked #breadsticks #foodporn,https://twitter.com/catfishman/status/12886249...
1,1288624228338749445,amypurple,14447726,#ebay #baking #cookbook,2020-07-29 23:55:32+00:00,,#ebay #baking #cookbook,https://twitter.com/amypurple/status/128862422...
2,1288621768651845632,luluontherun,160155438,Busy #baking today for our trip away this week...,2020-07-29 23:45:45+00:00,,#baking #bananabread #peanutbuttercookies #gra...,https://twitter.com/luluontherun/status/128862...
3,1288620775692480512,joyturingan,18208863,Hey friends! Need just 125 subscribers on my c...,2020-07-29 23:41:48+00:00,,#sourdoughbread #yout #vlogger #cookingchannel...,https://twitter.com/joyturingan/status/1288620...
4,1288619465286901762,FejjMall,1276946641489199106,Reusable Silicone Leakproof Food Storage Ziplo...,2020-07-29 23:36:36+00:00,,#cook #baking #fejjmall #bakery #bread #pastry...,https://twitter.com/FejjMall/status/1288619465...
...,...,...,...,...,...,...,...,...
9995,1029941023680516096,FarandWidecom,974356729856053248,Here's how to avoid throngs of tourists at the...,2018-08-16 04:00:50+00:00,,,https://twitter.com/FarandWidecom/status/10299...
9996,1029940978495287296,FarandWidecom,974356729856053248,The most visited tourist attractions in the wo...,2018-08-16 04:00:39+00:00,,,https://twitter.com/FarandWidecom/status/10299...
9997,1029940887135039489,FarandWidecom,974356729856053248,The most visited tourist attractions in the wo...,2018-08-16 04:00:17+00:00,,,https://twitter.com/FarandWidecom/status/10299...
9998,1029940887135039489,FarandWidecom,974356729856053248,The most visited tourist attractions in the wo...,2018-08-16 04:00:17+00:00,,,https://twitter.com/FarandWidecom/status/10299...
9999,1029940887135039489,FarandWidecom,974356729856053248,The most visited tourist attractions in the wo...,2018-08-16 04:00:17+00:00,,,https://twitter.com/FarandWidecom/status/10299...

In [104]:
bakingdata['id'].nunique()

9543

In [114]:
bakingdata

,id,username,author_id,text,date,geo,hashtags,permalink
0,1288624943647936513,catfishman,14279889,Got bored and had the munchies so I made garli...,2020-07-29 23:58:22+00:00,,#bread #baking #getbaked #breadsticks #foodporn,https://twitter.com/catfishman/status/12886249...
1,1288624228338749445,amypurple,14447726,#ebay #baking #cookbook,2020-07-29 23:55:32+00:00,,#ebay #baking #cookbook,https://twitter.com/amypurple/status/128862422...
2,1288621768651845632,luluontherun,160155438,Busy #baking today for our trip away this week...,2020-07-29 23:45:45+00:00,,#baking #bananabread #peanutbuttercookies #gra...,https://twitter.com/luluontherun/status/128862...
3,1288620775692480512,joyturingan,18208863,Hey friends! Need just 125 subscribers on my c...,2020-07-29 23:41:48+00:00,,#sourdoughbread #yout #vlogger #cookingchannel...,https://twitter.com/joyturingan/status/1288620...
4,1288619465286901762,FejjMall,1276946641489199106,Reusable Silicone Leakproof Food Storage Ziplo...,2020-07-29 23:36:36+00:00,,#cook #baking #fejjmall #bakery #bread #pastry...,https://twitter.com/FejjMall/status/1288619465...
...,...,...,...,...,...,...,...,...
9995,1029941023680516096,FarandWidecom,974356729856053248,Here's how to avoid throngs of tourists at the...,2018-08-16 04:00:50+00:00,,,https://twitter.com/FarandWidecom/status/10299...
9996,1029940978495287296,FarandWidecom,974356729856053248,The most visited tourist attractions in the wo...,2018-08-16 04:00:39+00:00,,,https://twitter.com/FarandWidecom/status/10299...
9997,1029940887135039489,FarandWidecom,974356729856053248,The most visited tourist attractions in the wo...,2018-08-16 04:00:17+00:00,,,https://twitter.com/FarandWidecom/status/10299...
9998,1029940887135039489,FarandWidecom,974356729856053248,The most visited tourist attractions in the wo...,2018-08-16 04:00:17+00:00,,,https://twitter.com/FarandWidecom/status/10299...
9999,1029940887135039489,FarandWidecom,974356729856053248,The most visited tourist attractions in the wo...,2018-08-16 04:00:17+00:00,,,https://twitter.com/FarandWidecom/status/10299...

In [88]:
bakingtest

,id,username,author_id,text,date,geo,hashtags,permalink
0,1288624943647936513,catfishman,14279889,Got bored and had the munchies so I made garli...,2020-07-29 23:58:22+00:00,"Calgary, Alberta",#bread #baking #getbaked #breadsticks #foodporn,https://twitter.com/catfishman/status/12886249...
2,1288624943647936513,amypurple,14447726,#ebay #baking #cookbook,2020-07-29 23:55:32+00:00,"Calgary, Alberta",#ebay #baking #cookbook,https://twitter.com/amypurple/status/128862422...
3,1288624943647936513,luluontherun,160155438,Busy #baking today for our trip away this week...,2020-07-29 23:45:45+00:00,"Calgary, Alberta",#baking #bananabread #peanutbuttercookies #gra...,https://twitter.com/luluontherun/status/128862...
4,1288624943647936513,joyturingan,18208863,Hey friends! Need just 125 subscribers on my c...,2020-07-29 23:41:48+00:00,"Calgary, Alberta",#sourdoughbread #yout #vlogger #cookingchannel...,https://twitter.com/joyturingan/status/1288620...
5,1288624943647936513,FejjMall,1276946641489199106,Reusable Silicone Leakproof Food Storage Ziplo...,2020-07-29 23:36:36+00:00,"Calgary, Alberta",#cook #baking #fejjmall #bakery #bread #pastry...,https://twitter.com/FejjMall/status/1288619465...
6,1288624943647936513,HappyRunner8,318401590,My belly is full!! Chicken tikka masala and pe...,2020-07-29 23:33:00+00:00,"Calgary, Alberta",#homemade #homecooking #tikkamasala #peachcobb...,https://twitter.com/HappyRunner8/status/128861...
7,1288624943647936513,SarahFegleyCY,769836229,Summer Cheesecake Tart https://sarahfegley.com...,2020-07-29 23:32:41+00:00,"Calgary, Alberta",#cooking #food #foodie #homemade #yummy #foodp...,https://twitter.com/SarahFegleyCY/status/12886...
8,1288624943647936513,skypasstreats,1286686240058814466,Something is coming and I canâ€™t wait to show y...,2020-07-29 23:29:03+00:00,"Calgary, Alberta",#skypasstreats #cooking #baking #fun #chillvibes,https://twitter.com/skypasstreats/status/12886...
9,1288624943647936513,tmj_IDA_HRTA,105053000,"See our latest Meridian, ID Hospitality job op...",2020-07-29 23:27:17+00:00,"Calgary, Alberta",#Baker #Baking,https://twitter.com/tmj_IDA_HRTA/status/128861...
10,1288624943647936513,RepeatRG,4837535942,My first order if cloud bread is done #ketorec...,2020-07-29 23:27:12+00:00,"Calgary, Alberta",#ketorecipes #cloudbread #newthings #bakedgood...,https://twitter.com/RepeatRG/status/1288617101...